spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <<your_client_id_here>>
            client-secret: <<your_client_secret_here>>
            scope: profile, email
          github:
            client-id: <<your_client_id_here>>
            client-secret: <<your_client_secret_here>>
            scope: read:user, user:email

app:
  jwt:
    secret: mysecretkeyisthisvgfnhgfhgfhjgfjhdrftgwetfdgdfhgfjx
    expiration:
      minutes: 10
  oauth2:
    redirectUri: http://localhost:8080/home